"""Browser-based cookie extraction for YouTube using Playwright (headless).

Uses the synchronous Playwright API so it can be called safely from
thread-pool executors without event-loop conflicts.
"""

import time
from pathlib import Path
from typing import Any

from bot.utils.logger import logger

# Cookie file path
_COOKIE_CACHE_DIR = Path(__file__).resolve().parent.parent / "data"
_COOKIE_FILE = _COOKIE_CACHE_DIR / "youtube_cookies.txt"
_COOKIE_MAX_AGE = 3600  # Refresh cookies every hour


def _cookies_are_fresh() -> bool:
    """Check if cached cookies exist and are not expired."""
    if not _COOKIE_FILE.exists():
        return False
    age = time.time() - _COOKIE_FILE.stat().st_mtime
    return age < _COOKIE_MAX_AGE


def _format_netscape_cookie(cookie: dict[str, Any]) -> str:
    """Format a cookie dict into Netscape cookie file format."""
    domain = cookie.get("domain", "")
    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    path = cookie.get("path", "/")
    secure = "TRUE" if cookie.get("secure", False) else "FALSE"
    expires = str(int(cookie.get("expires", 0)))
    name = cookie.get("name", "")
    value = cookie.get("value", "")
    return f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expires}\t{name}\t{value}"


def extract_youtube_cookies_sync() -> str | None:
    """
    Launch a headless browser, visit YouTube, and extract cookies.

    Uses the synchronous Playwright API so it can be called from a thread
    executor without conflicting with the running asyncio event loop.

    Returns path to cookies.txt file or None on failure.
    """
    if _cookies_are_fresh():
        logger.info("Using cached YouTube cookies from %s", _COOKIE_FILE)
        return str(_COOKIE_FILE)

    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        logger.warning("Playwright not installed — cannot extract browser cookies")
        return None

    logger.info("Extracting YouTube cookies via headless browser...")

    try:
        with sync_playwright() as p:
            browser = p.chromium.launch(
                headless=True,
                args=[
                    "--disable-blink-features=AutomationControlled",
                    "--no-sandbox",
                    "--disable-dev-shm-usage",
                    "--disable-gpu",
                ],
            )

            context = browser.new_context(
                user_agent=(
                    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/131.0.0.0 Safari/537.36"
                ),
                viewport={"width": 1920, "height": 1080},
                locale="en-US",
            )

            page = context.new_page()

            # Visit YouTube to generate cookies
            page.goto(
                "https://www.youtube.com",
                wait_until="domcontentloaded",
                timeout=30000,
            )

            # Wait for cookies to be set
            page.wait_for_timeout(3000)

            # Accept consent if prompted (EU/GDPR)
            try:
                consent_btn = page.locator(
                    'button:has-text("Accept all"), '
                    'button:has-text("Accept"), '
                    'button:has-text("I agree"), '
                    'button[aria-label*="Accept"]'
                )
                if consent_btn.count() > 0:
                    consent_btn.first.click()
                    page.wait_for_timeout(2000)
            except Exception:
                pass

            # Navigate to a video page to trigger more cookie generation
            try:
                page.goto(
                    "https://www.youtube.com/watch?v=jNQXAC9IVRw",
                    wait_until="domcontentloaded",
                    timeout=20000,
                )
                page.wait_for_timeout(2000)
            except Exception:
                pass

            # Extract cookies
            cookies = context.cookies("https://www.youtube.com")

            browser.close()

        if not cookies:
            logger.warning("No cookies extracted from YouTube")
            return None

        # Write cookies in Netscape format
        _COOKIE_CACHE_DIR.mkdir(parents=True, exist_ok=True)

        lines = ["# Netscape HTTP Cookie File", "# Generated by Media Magic Bot", ""]
        for cookie in cookies:
            lines.append(_format_netscape_cookie(cookie))

        _COOKIE_FILE.write_text("\n".join(lines) + "\n")
        logger.info(
            "Extracted %d YouTube cookies to %s", len(cookies), _COOKIE_FILE
        )
        return str(_COOKIE_FILE)

    except Exception as e:
        logger.error("Failed to extract YouTube cookies: %s", e)
        return None


def get_cached_cookie_path() -> str | None:
    """Return path to cached cookies if they exist, else None."""
    if _COOKIE_FILE.exists():
        return str(_COOKIE_FILE)
    return None
